background {
	monitor =
	color = rgba(000000ff)
}

input-field {
	monitor =
	size = 250, 50
	position = 0, 0
	dots_center = true
	fade_on_empty = false
	placeholder_text = Contraseña...
}

label {
	monitor =
	text = Bloqueado
	font_size = 32
	position = 0, 100
}

